import type { Metadata } from 'next';
// import { Poppins } from "next/font/google";
import '@/styles/globals.css';
import Nav from '@/sections/nav';
import Footer from '@/sections/footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Nav />
        <main className="container mx-auto w-full max-w-screen-2xl px-4 lg:px-[101px]">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
