import type { Metadata } from "next";
// import { Poppins } from "next/font/google";
import "@/styles/globals.css";
import Nav from "@/sections/home/nav";

// const poppins = Poppins({
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
//   display: "swap",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Nav />
        <main className="lg:px-[101px] px-4 w-full mx-auto container max-w-screen-2xl">
          {children}
        </main>
      </body>
    </html>
  );
}
