import type { Metadata } from 'next';
import { Toaster } from 'sonner';
import '@/styles/globals.css';
import Nav from '@/components/nav';
import Footer from '@/components/footer';
import ContractProvider from '@/connect-wallet';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ContractProvider>
          <Nav />
          <main className="container mx-auto w-full max-w-screen-2xl px-4 lg:px-[101px]">
            {children}
          </main>
          <Toaster position="bottom-right" />
          <Footer />
        </ContractProvider>
      </body>
    </html>
  );
}
